/* ============ EPILOGHI PERSONALI E IMPRESE (achievement) — LA CASA CHE NON FINISCE ============ */

/* Epiloghi per persona, per tipo di finale:
   'parola'  = Daniele vince il Duello finale: Eleinad smontato fallacia per fallacia (e_parola)
   'gemelli' = la foto ricomposta: il demone non regge due che smettono di litigare (e_gemelli)
   'colori'  = vittoria in battaglia, colpo di grazia col Guscio Blu (e_colori)
   'scambio' = qualcuno è rimasto sul Divano al posto di Daniele (e_scambio)
   NOTA scambio: i testi NON nominano mai chi è rimasto — devono funzionare per qualunque scelta. */

const HERO_EPILOGUES = {

  gaetano: {
    parola: `Gaetano ha riacceso il telefono il giorno dopo, e la prima notifica era di Luca Giunti: "Prof, giovedì ho la verifica. Facciamo 4 ore?". Ha risposto sì. UN'ora, giovedì alle 18, "e il libro stavolta lo apri PRIMA". In ufficio, tra i satelliti, ha preso un'abitudine nuova che non spiega a nessuno: quando un collega risponde a monosillabi per più di due giorni, Gaetano si presenta alla scrivania con due caffè e nessuna scusa pronta. E nella chat dei sei c'è una regola fissata in alto, scritta da lui: "Se qualcuno DIMINUISCE, si cita Cialdini e si va a citofonare." Nessuno ha mai chiesto cosa significhi. Nessuno ne ha bisogno.`,
    gemelli: `Tornato a casa, Gaetano ha fatto una cosa che non racconta: ha misurato il suo corridoio. Tre metri e venti, andata e ritorno, IDENTICI. Ha rimesso il metro nel cassetto e ha dormito undici ore. Adesso, quando Federico e Daniele litigano in chat — succede ancora, ogni giorno, su tutto — non fa più da arbitro: mette un cuore a entrambi e scrive "dati insufficienti, richiedo confronto dal vivo". Il confronto dal vivo finisce a Mario Kart, che è il tribunale giusto. E sulla scrivania, tra i modellini di satellite, è comparsa una cornice piccola: la foto dei gemelli ricomposta, con lo scotch bene in vista. L'ha voluta così. "La riparazione fa parte della struttura."`,
    colori: `La prima domenica utile Gaetano era in spiaggia coi racchettoni, e i bagnini giurano che lo smash non ha mai fischiato così. Ha ripreso le ferie vere: telefono in modalità aereo, NESSUNA emergenza autorizzata — con un'eccezione sola, salvata tra i preferiti, che squilla anche in aereo. Al lavoro gli hanno chiesto com'è andata la settimana di pausa e lui ha risposto "movimentata, strutturalmente istruttiva", che per Gaetano è un poema epico. E quando uno dei suoi satelliti passa sopra la città, se può, controlla le immagini del quartiere di Daniele: i tetti riflettono normale, le finestre sono accese. Lo verifica lo stesso. Il metodo scientifico non va in ferie.`,
    scambio: `Gaetano ha un file che si chiama RIENTRO, versione ventuno. Piante ricostruite a memoria, turni, zaini, tre piani alternativi con analisi dei rischi. Ogni primo venerdì del mese il gruppo si trova a casa sua, si mangia, si aggiorna il file, e nessuno usa mai la parola "se": solo "quando". Ha spiegato ai colleghi che il venerdì sera è "manutenzione programmata" e non ha aggiunto altro. Perché Gaetano progetta satelliti, e i satelliti gli hanno insegnato la cosa che adesso tiene insieme tutti: un segnale che non risponde non è un segnale perso. È un segnale che aspetta la finestra giusta per il contatto. E la finestra, prima o poi, si apre.`,
  },

  natalino: {
    parola: `Natalino il martedì chiude il salone un'ora prima. Alle clienti dice "inventario". L'inventario è il divano di Daniele: carte, un tronello rollato con la cura delle grandi occasioni — uno solo, se lo fumano a metà — e chiacchiere fino a tardi, come nelle sere lunghe di prima. Solo che adesso la finestra è aperta e la porta pure. Della notte nella Casa non parla quasi mai; solo una volta, a una cliente che fissava il vuoto nello specchio, ha detto piano: "Amore mio, il grigio è un colore che si copre. Lo facciamo di mestiere." La signora ha riso senza sapere perché. È uscita col taglio più bello del quartiere.`,
    gemelli: `Natalino adesso taglia i capelli ai gemelli lo stesso giorno, poltrone adiacenti, uno specchio a testa. Litigano per tutti i quaranta minuti — sulla riga, sulla schiuma, su chi dei due "porta meglio il taglio" — e lui lavora in mezzo al fuoco incrociato con la serenità di un casco da sminatore. Alla cassa fa pagare uno solo: "il secondo è omaggio del gemello", e ogni volta cambia quale, così litigano anche su quello. Alle clienti che chiedono chi sono quei due identici che urlano, risponde: "Fratelli. Si vogliono un bene dell'anima. Si sente da fuori, no?" E in effetti, a saperlo ascoltare, si sente.`,
    colori: `Il primo taglio, Natalino, gliel'ha fatto a casa: Daniele sul divano, asciugamano sulle spalle, le forbici giapponesi uscite dalla custodia per l'occasione. Tre mesi di Grigiore vengono via a ciocche, e Natalino non fa una piega, letteralmente: lavora, commenta la Switch, esige una Coca Zero come compenso. Solo alla fine, spazzolando via i capelli, dice: "Ecco. Ricrescono sempre, lo sai? È il loro unico difetto professionale." Daniele allo specchio si riconosce, e questo — Natalino lo sa fare il suo mestiere — non è un dettaglio. Adesso il taglio si fa una volta al mese, sempre a casa, sempre sul divano. Il divano ha smesso di essere un posto dove sparire. È un posto dove ci si trova.`,
    scambio: `Natalino tiene sempre due tronelli di scorta rollati, come quella notte. Uno è per il viaggio — il primo venerdì del mese, quando il gruppo torna davanti al portone — e uno non si tocca: sta nella custodia delle forbici giapponesi, avvolto nella velina, "per quando esce". Non dice mai un nome, dice "quando esce", e lo dice con il tono con cui si prenota un appuntamento: certo, calendarizzato, non negoziabile. Al salone ha aggiunto un servizio non in listino che fa solo lui e solo a fine giornata: ascoltare. Ha scoperto che il Grigiore, fuori dalla Casa, gira ancora — e che un parrucchiere bravo lo vede in ricrescita, prima di tutti.`,
  },

  claudia: {
    parola: `Claudia ha ancora tutti gli screenshot della chat di Daniele: quelli in cui diminuiva, messaggio dopo messaggio, fino al visualizzato e basta. Non li ha cancellati. Li ha messi in un album che si chiama "MAI PIÙ SENZA CITOFONARE", e l'album lavora: adesso il suo occhio assoluto — quello che nota una porta spostata, un riflesso storto — sta puntato sulle persone. Un'amica che risponde corto da tre giorni, un collega che dà buca due volte: Claudia non scrive "tutto ok?", Claudia si presenta. Al lavoro l'hanno promossa per "capacità di lettura del sentiment". Lei ha ringraziato senza correggere. Il sentiment. Certo. Chiamiamolo così.`,
    gemelli: `La foto ricomposta l'ha stampata Claudia, ovviamente: due copie in alta qualità, una per gemello, con una regola scritta dietro nella sua grafia — "NON restaurare lo strappo". L'originale, quello con lo scotch, l'hanno voluto loro due, incorniciato, e Claudia ha dovuto arbitrare quaranta minuti di lite su in quale casa dovesse stare. Ha deciso: sei mesi ciascuno, con passaggio di consegne alla cena di famiglia, verbalizzato in chat. Funziona. E nel suo telefono, in mezzo a diecimila immagini perfette per lavoro, la preferita adesso è quella venuta peggio: mossa, storta, due gemelli che si abbracciano ridendo mentre uno dei due sicuramente sta ancora avendo ragione.`,
    colori: `Claudia ha aperto un album privato che si chiama "COLORE": una foto al giorno di una cosa viva. Il verde bottiglia dell'IPA di Gaetano controluce, il giallo delle birre al limone, il rosa shock di uno spray Kerastase, la curva arcobaleno di Mario Kart in pausa sullo schermo di Daniele. Nessun filtro, nessuna caption, nessuna pubblicazione: è l'unico progetto della sua carriera senza pubblico, e forse per questo è quello che cura meglio. Ai racchettoni è tornata più cattiva di prima — la ghigliottina adesso ha una motivazione — e quando Gaetano le chiede dove trova il tempo per l'album, risponde con l'unica analitica che conta: "Il colore va documentato. Ho visto cosa succede quando nessuno guarda."`,
    scambio: `Claudia ha una foto come blocco schermo: i sei, tutti insieme, non ritagliata. La guarda un numero di volte al giorno che non dichiara. È lei che documenta i rientri del primo venerdì del mese — ora, meteo, dettagli del portone, OGNI dettaglio del portone — perché Claudia sa una cosa che gli altri sperano soltanto: le case che barano prima o poi si tradiscono, un riflesso storto, una finestra che non torna, e quando succederà lei avrà il confronto fotografico pronto. Nel frattempo tiene aggiornato un album condiviso coi cinque, titolo: "MATERIALE PER IL RITORNO". Ultima foto caricata: una sedia vuota a una tavolata, apparecchiata comunque. Didascalia: "Si tiene il posto."`,
  },

  federico: {
    parola: `Federico l'ha vista con i suoi occhi: suo fratello che smonta un demone con la retorica, tre passaggi, davanti a tutti. Da allora nei meeting importanti cita "un consulente esterno che non è sul mercato", e quando i clienti chiedono chi sia, sorride da consulente: "Il migliore del settore. Ha vinto l'unica trattativa che contava." Le birre al limone sono scese a nove al giorno — la decima resta nel frigo di Daniele, sempre, rimpiazzata a ogni visita: non è scaramanzia, "è SCIENZA". E litigano ancora, ovvio, ogni giorno, su tutto: adesso soprattutto su chi ha vinto davvero quella notte. Federico sostiene che il merito è di chi gli ha insegnato a litigare per trent'anni. Per una volta, forse, hanno ragione tutti e due.`,
    gemelli: `La foto ricomposta Federico la tiene nel portafoglio, dove teneva i biglietti da visita importanti. Non lo dice a nessuno e lo sanno tutti. Con Daniele litigano ancora dal 1994 — chi ha ragione, i soldi, la pastella dei pancakes — ma è cambiata una cosa sola, e cambia tutto: il giovedì è fisso. Casa di Daniele, Mario Kart, birre al limone e Coca Zero sullo stesso tavolino, e una briscola finale che va comunque arbitrata. Un cliente una volta gli ha chiesto il segreto per "gestire i conflitti in famiglia". Federico ha tirato fuori la foto, l'ha mostrata senza spiegare lo scotch, e ha detto l'unica frase non fatturabile del suo repertorio: "Non si gestiscono. Si tengono."`,
    colori: `La rivincita a Mario Kart si è giocata il giovedì dopo, casa di Daniele, porta aperta, tutti e sei sul divano — il divano, sì, riabilitato per buona condotta. Federico era primo all'ultima curva dell'ultimo giro, e il Guscio Blu è arrivato puntuale come una bolletta. Ha urlato al complotto per dieci minuti, ha chiesto la revisione al VAR, ha minacciato un esposto alla Nintendo. Poi ha aperto una birra al limone e l'ha toccata contro la Coca Zero di suo fratello, che rideva come non lo sentiva ridere da un anno. Adesso in agenzia ha una regola per i pitch: "Il colpo migliore è quello che colpisce il primo. Chiedete a mio fratello." Nessuno capisce. Fattura lo stesso.`,
    scambio: `Federico ha risolto come risolve tutto: lavorando il doppio. È lui che coordina i rientri del primo venerdì — logistica, orari, "il portone non risponde ma noi presidiamo il territorio" — ed è lui che ha già pronto il documento che nessuno gli ha chiesto: quaranta pagine intitolate "PROPOSTA DI RINEGOZIAZIONE", destinatario Eleinad, oggetto: uno scambio al contrario. Gaetano dice che non funzionerà così. Federico risponde che TUTTO è negoziabile, che il demone ha già accettato uno scambio una volta, quindi c'è un precedente, quindi c'è un margine. Intanto ogni venerdì porta le birre al limone per tutti, più una che non apre nessuno. La lascia sul davanzale del portone, andandosene. Caparra.`,
  },

  emanuela: {
    parola: `Emanuela ha rimesso a posto la borsa Kerastase il giorno dopo, ripristino completo: garze, spray, taralli. Ma c'è un ripiano nuovo, quello che lei chiama "il kit del cognato saggio": una Coca Zero fredda, un mazzo di carte e la lista dei giovedì già pianificati fino a Natale. Perché Daniele l'ha smontato lei per prima, il Grigiore, quando ha capito cos'era: un vibe-killer. Il definitivo, il capo di tutti i molestatori di feste — e i vibe-killer, con Emanuela, hanno vita breve. Al salone adesso ha un radar tarato fino: la cliente che entra spenta, che parla piano, che dice "niente, tutto uguale". Quaranta minuti dopo esce con la piega e con un colore addosso che non è solo tinta. Nessuno sa come fa. Lei sì: pratica.`,
    gemelli: `Alle cene della domenica, Emanuela si siede sempre tra i gemelli: posizione storica, ruolo istituzionale. Solo che adesso ha cambiato metodo. Prima disinnescava — una mano sul braccio, "amore, l'arrosto si fredda" — adesso li lascia litigare, perché quella notte ha visto cosa succede quando due che si vogliono bene smettono di dirselo anche urlando. Ha messo una regola sola: il timer. "Tre minuti a testa, poi si vota." Votano sempre gli altri quattro, vince sempre l'arrosto. E quando Federico, a casa, le chiede se secondo lei aveva ragione lui, Emanuela risponde ogni volta la stessa cosa, da Gaeta, definitiva: "Avevi ragione tu. E pure lui. Siete gemelli pure in questo, che ci volete fare."`,
    colori: `Emanuela ha deciso che il colore si somministra: dosi piccole, costanti, professionali. Sul comodino di Daniele è comparsa una conchiglia di Gaeta — "tienila, che il mare fa rumore anche da ferma" — e a giugno l'ha portato al mare per davvero, tutti e sei, ombrelloni in fila. Daniele si è lamentato della sabbia, del sole, dei racchettoni di Gaetano e Claudia che "sono un pericolo balistico". È rimasto fino al tramonto. Al salone, intanto, ha inventato un trattamento che non è sul listino e non ha nome: quando arriva una testa spenta, lei ci mette più tempo, più mani e una chiacchiera di quelle vere. Natalino la guarda e non dice niente. Certe colleghe si ringraziano lavorando.`,
    scambio: `La borsa Kerastase adesso vive accanto alla porta, pronta, controllata ogni domenica: garze, taralli freschi — li rinnova lei, "perché quando esce avrà fame" — una torcia, un cambio, e una cosa avvolta nella carta velina che non fa vedere a nessuno. Il primo venerdì del mese è lei che sveglia tutti coi messaggi vocali all'alba, lei che porta il caffè della moka buona davanti al portone, lei che all'andata canta e al ritorno pure, PIÙ forte, perché il silenzio in macchina non lo concede a nessuno, tantomeno al Grigiore. "Nessuno si spegne", aveva detto quella notte. Non era una frase. Era un contratto, e Emanuela i suoi contratti li onora tutti: chiedete alle sue clienti, chiedete ai suoi amici. Chiedete a chi aspetta.`,
  },

  daniele: {
    parola: `Daniele si è ripreso la vita a modo suo: piano, senza proclami. Il divano, i libri, la Switch, la Coca Zero in quantità industriale — tutto al suo posto, ma con una variabile nuova: la porta aperta e della gente dentro. Il Cialdini è tornato sul comodino, sottolineato adesso in QUATTRO colori: il quarto è per i trucchi che ha visto usare dal vivo. E la leggendaria serata D&D, quella del biglietto — "un giorno li porto a giocare" — si è fatta davvero: sette set di dadi comprati da lui, uno a testa più uno di scorta, Daniele dietro lo schermo del master con la calma di chi ha già vinto il boss più difficile della sua vita. Federico ha detto che era da sfigati. Ha giocato più forte di tutti. Come da manuale.`,
    gemelli: `La foto ricomposta sta sulla mensola di Daniele, scotch in vista, e nessuno la può toccare: "la riparazione fa parte della foto". Con Federico litigano ancora, ogni giorno, per fortuna — sulla pastella dei pancakes hanno raggiunto il trentunesimo anno di contenzioso — ma il giovedì è sacro: Mario Kart, la briscola arbitrata, la Coca Zero e le birre al limone che si toccano nel brindisi più stonato d'Italia. Daniele ha ricominciato dai libri, poi dalla casa, poi dal resto, con i suoi tempi: nessuno lo mette fretta e lui non finge date. Solo una cosa l'ha fatta subito: cinque copie delle chiavi nuove, una a testa. "Così la prossima volta non serve quella di scorta." La prossima volta, ha detto. Al futuro. Suona benissimo.`,
    colori: `Il Guscio Blu l'ha tirato lui, e nessuno gli toglierà mai questa soddisfazione: colpisce sempre, e colpisce il primo. Poi la vita è ripartita come voleva lui: piano. Il divano è rimasto — "il divano non ha colpe" — ma l'ha girato verso la finestra, che è un dettaglio da niente e invece è tutto. I libri, la Switch, la Coca Zero: tutto uguale, tutto diverso, perché il giovedì la casa si riempie e il sabato qualcuno passa "per caso" con le birre al limone, e il caso, ha notato Daniele, ha una puntualità sospetta. La serata D&D promessa si è fatta: lui master, i dadi comprati per tutti, Federico che dichiarava "roba da sfigati" tirando il d20 come se fosse una finale. Sul frigo, un biglietto nella sua grafia: "ANCORA UN COLORE." Ogni giorno ne aggiunge uno. La lista non finisce. Stavolta è una bella notizia.`,
    scambio: `Daniele è uscito con le gambe che non ricordavano il mondo, e con un peso che nessuno gli ha permesso di portare da solo: qualcuno è rimasto seduto al posto suo. Da quel giorno non spreca niente. Studia — il Manuale Annotato ha una seconda edizione, riscritta a memoria, corretta e AMPLIATA — perché nessuno conosce la Casa da dentro come lui, e al primo venerdì del mese è sempre il primo davanti al portone, puntualissimo, lui che non era puntuale a niente. La serata D&D si fa lo stesso, ogni mese: è un ordine, non un'abitudine. Sette set di dadi sul tavolo, una sedia apparecchiata che resta vuota e non si sposta. "Quando torna, deve trovare il posto pronto", dice Daniele. Quando. Mai "se". Su questo, per la prima volta nella storia, sono tutti d'accordo.`,
  },

};

/* ---------- IMPRESE — achievement di fine partita ---------- */
/* Ogni voce: { flag, icon, title, desc } — sbloccata se G.flags[flag] è veritiero. */

const IMPRESE = [
  { flag: 'finestra_vista',        icon: '🪟', title: 'Il Panorama Sbagliato',        desc: 'Avete guardato fuori dalla finestra di Daniele. Fuori non era d\'accordo.' },
  { flag: 'voce_sbagliata',        icon: '📺', title: 'Doppiaggio Fuori Sync',        desc: 'La voce dalla TV era quella di Daniele. Le pause no. Ve ne siete accorti.' },
  { flag: 'nota_daniele',          icon: '📝', title: 'Il Primo Segnale',             desc: 'Un biglietto nella grafia di Daniele: tre giorni da solo là dentro, e già vi lasciava indicazioni.' },
  { flag: 'misure_impossibili',    icon: '📐', title: 'Il Metro Non Mente',           desc: 'Gaetano ha misurato il corridoio due volte. La seconda era più lungo. Il metro è a posto: è la casa che bara.' },
  { flag: 'gocce_trovate',         icon: '💧', title: 'Il Dottore Sa il Fatto Suo',   desc: 'Le Gocce del Dottore, trovate dove Daniele le teneva con cura. Fanno vedere quello che il Grigiore nasconde.' },
  { flag: 'rifiuto_stile',         icon: '🛋', title: 'No, Grazie: Si Sta Scomodi',   desc: 'Eleinad vi ha offerto il divano. Avete rifiutato con una battuta che gli brucia ancora.' },
  { flag: 'federico_insulto',      icon: '🎤', title: 'Pitch Aggressivo, Uso Improprio', desc: 'Federico ha insultato un demone con precisione da consulente. Il demone ha chiesto una pausa.' },
  { flag: 'eleinad_teme_gemelli',  icon: '👥', title: 'Due È Troppo',                 desc: 'Avete visto Eleinad esitare davanti ai gemelli fianco a fianco. Anche i mostri hanno paure.' },
  { flag: 'duello_tutorial_vinto', icon: '🗣', title: 'Prima Lezione di Retorica',    desc: 'Il primo Duello di Parole, vinto chiamando la fallacia giusta al primo colpo. Daniele avrebbe applaudito. Daniele HA applaudito.' },
  { flag: 'manuale_annotato_letto', icon: '📖', title: 'Sottolineato in Tre Colori',  desc: 'Il Cialdini di Daniele, annotato a margine: il manuale del nemico, scritto dalla sua vittima preferita.' },
  { flag: 'bibliotecario_amico',   icon: '📚', title: 'Recensione a Cinque Stelle',   desc: 'Il Bibliotecario voleva leggervi i pensieri peggiori. Gli avete dato qualcosa di meglio da leggere.' },
  { flag: 'bibliotecario_morto',   icon: '📕', title: 'Fine Prestito',                desc: 'Il Bibliotecario è tornato scaffale. Certi libri si chiudono da soli. Altri vanno chiusi.' },
  { flag: 'segreto_specchio',      icon: '🪞', title: 'Il Nome allo Specchio',        desc: 'Eleinad è Daniele letto al contrario: un parassita-specchio. La faccia è rubata. L\'anima NO.' },
  { flag: 'libro_cose_belle',      icon: '🌈', title: 'L\'Elenco delle Cose Belle',   desc: 'Il quaderno dove Daniele salvava quello che il Grigiore non doveva prendersi. L\'ha nascosto bene: sperava che lo trovaste voi.' },
  { flag: 'segreto_gemelli',       icon: '📷', title: 'La Crepa che Nutre',           desc: 'Il demone mangia dalla lite dei gemelli dal 1994. Trent\'anni di pasti gratis. Finiti.' },
  { flag: 'foto_ricomposta',       icon: '🩹', title: 'Lo Scotch Si Vede',            desc: 'La foto dei gemelli, strappata e ricomposta. La riparazione fa parte della foto.' },
  { flag: 'vibe_salvata',          icon: '🌺', title: 'Quaranta Secondi',             desc: 'Emanuela ha neutralizzato il Monologante come a una festa di Ibiza: sorriso, scusa perfetta, via.' },
  { flag: 'cuore_sommerso_preso',  icon: '🫀', title: 'Pescato a Mani Nude',          desc: 'Un Cuore di Colore sul fondale nero. Claudia sa cosa c\'era intorno. Qualcuno è sceso lo stesso.' },
  { flag: 'indizio_spiriti',       icon: '👻', title: 'Quello che i Vivi Non Vedono', desc: 'Uno Spirito vi ha indicato la strada. I morti del gruppo non hanno smesso di giocare.' },
  { flag: 'luca_promosso',         icon: '🎒', title: 'Quattro Ore, Un\'Ultima Volta', desc: 'Avete fatto lezione a Luca Giunti invece di combatterlo. Alle 21:00. Come sempre. Per l\'ultima volta.' },
  { flag: 'parmigiana_daniele',    icon: '🍆', title: 'L\'Unica Teglia a Colori',     desc: 'Nel frigo grigio, una parmigiana ancora viva: Daniele l\'aveva congelata per gli amici, "per quando venite".' },
  { flag: 'birre_ritrovate',       icon: '🍋', title: 'La Scorta Tattica',            desc: 'Le dieci birre al limone, ritrovate intatte. Federico le ha contate DUE volte. Poi le ha ricontate.' },
  { flag: 'segreto_trono',         icon: '🗝', title: 'La Mappa in Coca Zero',        desc: 'Le lattine in fila, le frecce, i segnali: la strada per il Trono, disegnata da Daniele una lattina alla volta.' },
  { flag: 'furto_riuscito',        icon: '🕶', title: 'Ai Danni del Banco',           desc: 'Avete derubato il Mercante Grigio nel suo stesso negozio. Il Riscossore non ha visto niente. Correte comunque.' },
  { flag: 'cuore_rubato_teca',     icon: '💎', title: 'La Teca Vuota',                desc: 'Nella teca del Mercante c\'era il colore di qualcuno. Ora non c\'è più: sta viaggiando verso casa.' },
  { flag: 'sonnambulo_salvato',    icon: '🌅', title: 'Uno su Tanti',                 desc: 'Nella Galleria avete svegliato qualcuno che il Grigiore aveva preso in un\'altra casa. Un pigiama che torna a essere una persona.' },
  { flag: 'sonnambuli_svegli',     icon: '⏰', title: 'Sveglia Generale',             desc: 'Tutta la Galleria in piedi, tutti gli schermi spenti riaccesi. Il Grigiore ha perso l\'intera collezione in una notte.' },
  { flag: 'zero_bevuta',           icon: '🥤', title: 'Un Brindisi al Collezionista', desc: 'Una Coca Zero di Daniele, bevuta nella casa che voleva spegnervi. Fredda. A COLORI. Alla sua salute.' },
  { flag: 'dentro_eleinad',        icon: '🫁', title: 'Non È Casa Sua',               desc: 'La casa non è l\'appartamento di Daniele: siete DENTRO Eleinad. E adesso lui sa che lo sapete.' },
  { flag: 'eleinad_vacilla',       icon: '🕳', title: 'Il Sorriso Fuori Asse',        desc: 'Per un momento la maschera è scivolata, e sotto non c\'era niente di pronto. L\'avete fatto vacillare.' },
  { flag: 'gemelli_pace',          icon: '🤝', title: 'Cessate il Fuoco (1994–oggi)', desc: 'Federico e Daniele d\'accordo su una cosa, insieme, ad alta voce. Il demone non aveva un piano per questo.' },
  { flag: 'eleinad_smontato',      icon: '🗣', title: 'Smontato in Tre Passaggi',     desc: 'Daniele ha vinto il Duello finale: fallacia per fallacia, davanti a tutti, con calma chirurgica. Il finale della Parola.' },
  { flag: 'eleinad_distrutto',     icon: '💥', title: 'Colpisce Sempre il Primo',     desc: 'Il Guscio Blu di Daniele sul nemico più forte, per rispetto della tradizione. Il finale dei Colori.' },
  { flag: 'finale_scambio',        icon: '🕯', title: 'Il Posto Apparecchiato',       desc: 'Qualcuno è rimasto sul Divano perché Daniele uscisse. Il gruppo non ha finito: si torna.' },
];

/* ---------- CRONACHE DELLA CASA ----------
   Righe di epilogo mondiale ("sei mesi dopo") mostrate nel finale SOLO se il flag è attivo. */

const CRONACA = [
  { flag: 'racchettoni_pronti', text: 'Sulla spiaggia di Gaeta, quest\'estate, due professionisti hanno tenuto la pallina in aria per quarantasette minuti. I bagnini hanno smesso di contare. Un bambino ha chiesto se erano supereroi. "No", ha risposto la madre, "sono FIDANZATI. È peggio."' },
  { flag: 'bivacco_fatto', text: 'La grigliata stile Pasquetta si è fatta, la domenica dopo. Pasta zucchine e gamberi in apertura, bruschette del maestro, e un brindisi che nessuno ha spiegato agli ospiti: sei bicchieri alzati verso il pavimento, "al pavimento, che non ci ha mai tradito".' },
  { flag: 'finale_parola',     text: 'Il giovedì sera, dall\'appartamento di Daniele, si sente ridere in sei. I vicini all\'inizio si preoccupavano — da quella porta non usciva un suono da mesi. Adesso, quando passano sul pianerottolo, rallentano apposta.' },
  { flag: 'finale_gemelli',    text: 'Un fotografo di quartiere ha ricevuto una foto strappata e ricomposta, da restaurare. Ha rifiutato il lavoro: "Lo scotch è la parte migliore." I due gemelli hanno pagato lo stesso, il doppio, e l\'hanno incorniciata com\'era.' },
  { flag: 'finale_colori',     text: 'Il condominio di Daniele ha votato di ridipingere le scale. Nessuno ricorda chi l\'abbia proposto, ma la delibera è passata all\'unanimità, con una sola prescrizione a verbale: "Qualsiasi colore, purché un colore."' },
  { flag: 'finale_scambio',    text: 'Ogni primo venerdì del mese, davanti a un portone di città, un gruppo di amici si presenta con uno zaino a testa. Il portone non si apre. Loro tornano il mese dopo. Il Grigiore, che ha tutto il tempo del mondo, comincia a sospettare che loro ne abbiano di più.' },
  { flag: 'bibliotecario_amico', text: 'Nella biblioteca comunale del quartiere è comparso uno scaffale nuovo: "Libri che vi vogliono bene". Consigli scritti a mano, calligrafia d\'altri tempi, mai firmati. Il bibliotecario umano lascia fare: le raccomandazioni sono SEMPRE giuste.' },
  { flag: 'sonnambulo_salvato', text: 'In un\'altra città, una famiglia ha riaperto la porta a qualcuno che mancava da mesi senza che nessuno sapesse dire dov\'era. Alla domanda "dove sei stato?" ha risposto solo: "Seduto. Poi degli amici che non conosco mi hanno svegliato."' },
  { flag: 'sonnambuli_svegli', text: 'Il salone di Natalino ed Emanuela ha una poltrona in più, l\'ultima in fondo, senza listino: "per chi ha giornate grigie". Ci si siede, si parla o non si parla, si esce col taglio in omaggio. Funziona più di quanto qualunque statistica registrerà mai.' },
  { flag: 'luca_promosso',     text: 'Luca Giunti ha passato la verifica VERA. Sette. Non sette e mezzo: SETTE, sudato e tutto suo. Ha scritto a Gaetano alle 21:00 in punto — "prof grazie" — e per la prima volta nella storia dell\'umanità un messaggio delle 21:00 ha fatto sorridere un insegnante.' },
  { flag: 'foto_ricomposta',   text: 'Nei portafogli di due gemelli viaggia la stessa foto, ricomposta, con lo scotch in vista. Quando litigano — succede, ogni giorno, su tutto — nessuno dei due la tira fuori. Sanno che c\'è. Basta quello.' },
  { flag: 'libro_cose_belle',  text: 'Il quaderno delle cose belle di Daniele adesso sta sul tavolino del salotto, in vista, a disposizione degli ospiti come le riviste dal parrucchiere. Ha pagine nuove, scritte in sei grafie diverse. Una delle voci recenti dice solo: "questo tavolino, il giovedì".' },
  { flag: 'pagina_strappata',  text: 'Al quaderno di Daniele manca ancora una pagina, e Daniele ha deciso di non riscriverla: "Le cose belle non fanno la copia carbone. Se ne scrivono di nuove." La finestra però la lascia aperta, caso mai al vento venisse voglia di restituirla.' },
  { flag: 'gemelli_pace',      text: 'Alla briscola di Natale, Federico e Daniele hanno giocato IN COPPIA per la prima volta dal 1994. Hanno perso. Hanno dato la colpa agli avversari, insieme, all\'unisono, con gli stessi gesti. Gli altri quattro considerano la sconfitta un miracolo perfettamente riuscito.' },
  { flag: 'zero_bevuta',       text: 'Nel frigo di Daniele c\'è sempre una fila di Coca Zero in più, "per gli ospiti". Gli ospiti, adesso, esistono: la fila va rifornita due volte a settimana. A Daniele lo scontrino della spesa non è mai sembrato così bello.' },
  { flag: 'gocce_trovate',     text: 'Un dottore ha trovato in studio una bottiglia di vino buono, senza biglietto. Ha chiesto alla segretaria: niente. Ha guardato l\'agenda dei pazienti, ha sorriso, e l\'ha messa via per un\'occasione speciale. Certe guarigioni si festeggiano così: in silenzio, e con un\'ottima annata.' },
  { flag: 'parmigiana_daniele', text: 'La parmigiana adesso si fa la domenica, a casa di Daniele: la teglia la porta Emanuela ma la ricetta la detta lui — "congelata era buona, fresca è un argomento INVINCIBILE". Federico non è d\'accordo. Federico si fa sempre il bis.' },
  { flag: 'cuore_rubato_teca', text: 'In una casa di un\'altra città c\'è una teca vuota che nessuno sa spiegare. Nello stesso quartiere, sei mesi dopo, una famiglia ha riabbracciato qualcuno che era rimasto grigio troppo a lungo. Le due cose, ufficialmente, non c\'entrano niente l\'una con l\'altra.' },
  { flag: 'daniele_sabota',    text: 'Di cosa abbia fatto Daniele da solo, tre giorni dentro la cosa che lo teneva, si sa poco: lui minimizza. Ma chi rilegge i segnali — le lattine in fila, le note, le trappole mancate per un soffio — arriva sempre alla stessa conclusione: il demone non stava vincendo. Stava PERDENDO tempo.' },
  { flag: 'ancora_colore_nota', text: 'Sul frigo di Daniele è appeso un biglietto nella sua grafia: "ANCORA UN COLORE." Sotto, ogni giorno, qualcuno ne aggiunge uno: il verde bottiglia dell\'IPA, il giallo delle birre al limone, il rosa Kerastase, il blu di un certo guscio. La lista è lunga. Non finisce. Stavolta è una bella notizia.' },
];
