/* Scena iniziale della campagna */
const CAMPAIGN_START = 'a0';

/* Rientra nella Casa: punti d'ingresso per rigiocare rami mai visti, sbloccati
   dopo il primo finale del profilo. Ogni capitolo prepara flag e zaino minimi. */
const CHAPTERS = [
  { id: 'a0',      prefixes: ['a'], label: '🌆 Sotto casa di Daniele', desc: 'Dall\'inizio: la chat muta, le chiavi di scorta, la porta che sparisce.' },
  { id: 's3',      prefixes: ['s'], label: '🩶 Il primo incontro', desc: 'Eleinad e il Contratto di Soggiorno. La faccia sbagliata di Daniele.', flags: { chiavi_prese: true } },
  { id: 'h1',      prefixes: ['h'], label: '🛋 Il Salotto-Cattedrale', desc: 'L\'hub delle tre gole: biblioteca, porte, cucina — e i momenti di respiro.', flags: { casa_aperta: true } },
  { id: 'b1',      prefixes: ['b'], label: '📚 La Biblioteca che Sussurra', desc: 'Il Bibliotecario, il Manuale Annotato, il segreto dello specchio.', flags: { casa_aperta: true } },
  { id: 'u1',      prefixes: ['u'], label: '🚪 Le Porte Sbagliate', desc: '1994, Gaeta in grigio, l\'Imbarco, la stanza che dice NON APRIRE.', flags: { casa_aperta: true } },
  { id: 'k1',      prefixes: ['k'], label: '🧊 La Cucina Fredda', desc: 'I segnali di Daniele, il Mercante Grigio, la Galleria dei Sonnambuli.', flags: { casa_aperta: true } },
  { id: 'm1',      prefixes: ['m'], label: '🎮 La Sala della Switch', desc: 'Il bozzolo, il Guardiano, la liberazione di Daniele.',
    flags: { casa_aperta: true, via_biblioteca: true, via_porte: true, segreto_gemelli: true },
    items: ['joycon_sinistro', 'lattina_zero', 'manuale_annotato'] },
  { id: 'z1',      prefixes: ['z', 'e_'], label: '🩶 La Cattedrale — tutte le carte in mano', desc: 'Il finale con ogni segreto e ogni arma: provate le vie che vi mancano.',
    addHero: 'daniele',
    flags: { casa_aperta: true, daniele_in_squadra: true, dentro_eleinad: true, segreto_specchio: true, segreto_gemelli: true, segreto_trono: true, foto_ricomposta: true, manuale_annotato_letto: true, daniele_sabota: true, zero_bevuta: true },
    items: ['manuale_annotato', 'foto_gemelli', 'cuore_colore', 'pallina_racchettoni', 'lattina_zero'] },
  { id: 'z1_puro', scene: 'z1', label: '🩶 La Cattedrale — a mani nude', desc: 'Il finale senza assi nella manica: la battaglia, lo scambio, la resa.',
    addHero: 'daniele',
    flags: { casa_aperta: true, daniele_in_squadra: true, dentro_eleinad: true } },
];

/* Il Diario della Notte: le conoscenze acquisite, in chiaro. Ordine = visualizzazione. */
const DIARY_FLAGS = [
  ['daniele_ringraziato',     '«CIAO DANIELE!» detto ad alta voce in mezzo al duello, e lui ha risposto con le luci. Il padrone di casa non ha una casella per la gratitudine: gli fa male sentirla.'],
  ['trucco_conosciuto',       'La frase sottolineata tre volte da Daniele: «Se conosci il trucco, il trucco non funziona. VALE ANCHE PER QUELLO GRANDE.» La terza sottolineatura era per voi.'],
  ['diciassette_firma',       'Il d20 sul tavolo della biblioteca, fermo sul diciassette, tirato da nessuno. Non era un buon segno: era una FIRMA. Federico se l\'è messo nella tasca dei documenti.'],
  ['scorta_di_blu',           'Nel catalogo dei colori, un blu cerchiato a penna: Serapo, ore 19:10. Daniele si era fatto la scorta PRIMA che qualcuno provasse a portargli via tutti gli altri. Non era nostalgia: era preparazione.'],
  ['mare_ha_risposto',        'Il sasso di Gaeta buttato al contrario: un mare morto ha battuto ciglio, e il cerchio è arrivato all\'orizzonte senza tornare. Emanuela non lo racconterà a nessuno, e lo racconterà a tutti.'],
  ['inventario_sbagliato',    'L\'inventario del Mercante, sbagliato in un modo nuovo. Niente paga — ma nemmeno il Grigiore sa contare, e il quadernone ci sopravviverà a tutti.'],
  ['trono_esposto',         'La presa di corrente di Eleinad: il Divano-Trono nella Sala della Switch, dove torna ogni notte a ricaricarsi di vita finta. "SCENDI DAL MIO DIVANO."'],
  ['nome_vero_detto',       'Il nome del demone, detto al rovescio davanti a testimoni: non un demone antico, un ANAGRAMMA. E la maschera si è crepata a metà.'],
  ['corsa_lettori_ok',      'La Traversata dei Lettori, vinta di slancio: la velocità decisa manda in confusione il catalogo del Grigiore. Teoria di Federico, campione statistico: uno.'],
  ['inventario_mercante',   'L\'inventario del Mercante, chiuso in cinque: il Grigiore non sa contare, e i numeri precisi detti ad alta voce lo innervosiscono da morire.'],
  ['nota_daniele',          'La nota di Daniele in cucina: "NON è una crisi: è un inquilino abusivo. Non ascoltate la mia faccia."'],
  ['sorriso_errore',        'Claudia ha visto cosa c\'è sotto il sorriso di Eleinad quando slitta: NIENTE. Un vuoto a forma di persona che ha imparato una faccia dalla finestra. Daniele è intero, altrove.'],
  ['cuore_studiato',        'Il Cuore di Colore, studiato: una riserva che CERCA un proprietario. Il Grigiore accumula e non prevede il reso — è il suo punto cieco.'],
  ['oblò_ispezionati',      'Nell\'ultimo oblò del sottoscala, un calendario con il 17 strappato via. Sotto la lavatrice: "IL 17 È MIO. NON È IN VENDITA. — D."'],
  ['quadro_studiato',       'Lo sportello blindato del sottoscala è blindato verso l\'INTERNO, e dentro qualcosa gratta da anni. La casa ha prigionieri suoi — e paure sue.'],
  ['ascoltato_porta',       'La voce dietro la porta, ascoltata a lungo: non parlava A voi. Ripassava. Le case che ripassano hanno un copione, e i copioni si possono rubare.'],
  ['muri_segnati',          'Trentaquattro metri di corridoio segnati col pennarello: le tacche non tornano mai due volte uguali. La casa si allunga quando non la misurate.'],
  ['messaggio_nascosto',    'Nella chat dei tre giorni, il messaggio nascosto di Daniele: le maiuscole fuori posto, lette in colonna, facevano una parola. Sapeva che sareste venuti a cercarla.'],
  ['daniele_ringraziato',   'Il grazie detto ad alta voce a Daniele, davanti al suo sabotaggio: le luci hanno sfarfallato DUE volte. Prego, ha risposto. A modo suo.'],
  ['inchiostro_finale',     'I finali regalati ai manoscritti hanno funzionato: l\'inchiostro fresco su pagine ferme da sessant\'anni. Certi libri aspettavano solo il permesso di finire.'],
  ['nastro_strappato',      'Il nastro del 1994 nella cameretta dei gemelli, strappato: trent\'anni di litigio registrato che nessuno riascolterà più. Qualche loop va spezzato a mano.'],
  ['bollette_incenerite',   'Le bollette del Mercante, incenerite: il debito che teneva in riga mezzo palazzo è estinto. La casa odia i conti che si chiudono senza di lei.'],
  ['archivio_perquisito',   'L\'archivio del Mercante, perquisito: ogni debito aveva un nome e ogni nome un piano del palazzo. La contabilità del Grigiore, nero su bianco.'],
  ['maschera_raccolta',     'La maschera di Eleinad, raccolta da terra dopo che è caduta: pesa NIENTE. Tutto quel terrore, e in mano è cartapesta grigia.'],
  ['divorente_distrutto',   'Il Divorente non si alza più: il divano che mangiava pomeriggi è tornato un divano. Comodo, pure — ma adesso si ALZA, la gente, quando vuole.'],
  ['telecomando_acceso',    'Il telecomando del Divorente, recuperato acceso: in memoria un comando solo, "RIMANDA.", premuto ogni notte alle tre e dieci — da FUORI, mentre in casa si dormiva. Non era Daniele che rimandava: era il Grigiore che gli rimandava indietro la vita.'],
  ['crepe_mappate',         'Le crepe del vuoto dietro l\'altare, mappate dagli spiriti: undici, tutte verso l\'alto, aperte solo se lo si guarda DI SBIECO. Frontale si fanno muro e ti mangiano il colpo. Il Grigiore ha la stessa fame delle sue crepe, e la fame non sa fingere.'],
  ['racchettoni_pronti',    'Il riscaldamento stile Gaeta: racchettoni in cattedrale, palleggio di riscaldamento compreso. Il colore, prima di combattere, si SCALDA.'],
  ['bivacco_fatto',         'Il bivacco per terra — MAI sul divano — nel cuore della casa nemica: taralli, turni di guardia, e la regola d\'oro: comodi mai, insieme sempre.'],
  ['daniele_vivo',          'Daniele è VIVO e combatte da dentro: sta nei fusibili, sabota quello che può. Non firmate, non sedetevi, non credete alla sua faccia.'],
  ['foto_gaeta_vista',      'La foto di Gaeta — il mare, gli amici, tutti bruciati e felici — resiste al Grigiore. I giorni troppo belli sono indigesti, per lui.'],
  ['daniele_sabota',        'I segnali di Daniele: le lattine di Coca Zero — le uniche cose a colori — disposte a freccia. Vi sta guidando LUI.'],
  ['misure_impossibili',    'Il corridoio misura 34 metri in un bilocale. La geometria qui dentro è un\'opinione della Casa.'],
  ['gocce_trovate',         'Le Gocce del Dottore, coi promemoria di Daniele: preso ✓, preso ✓, preso ✓ — fino a tre giorni fa. Si è fermato quando la casa l\'ha preso. Non prima. Il dottore sa il fatto suo.'],
  ['casa_aperta',           'La Casa ha tre gole: la Biblioteca che Sussurra, il corridoio delle Porte Sbagliate, la Cucina Fredda. Daniele è oltre, in alto, dove qualcosa guarda uno schermo da tre giorni.'],
  ['fumo_mappa',            'Il fumo del tronello ha disegnato la pianta: sopra tutto c\'è una sala con uno schermo e un divano. Il fumo batteva lì sopra, come un dito su un vetro.'],
  ['eleinad_teme_gemelli',  'Quando Federico l\'ha insultato, la voce di Eleinad è CAMBIATA: "Tu. Tu sei il GEMELLO." I gemelli gli fanno paura.'],
  ['segreto_specchio',      'SEGRETO: "Eleinad" è "Daniele" allo specchio — un parassita-riflesso, la fotocopia venuta male. Non è l\'anima di Daniele. E si VERGOGNA di ciò che è.'],
  ['manuale_annotato_letto','Avete letto le note di Daniele sul Manuale: conoscete le armi del nemico — riprova sociale, autorità, scarsità, fantoccio, falsa dicotomia, ricatto emotivo — PRIMA che le usi.'],
  ['ancora_colore_nota',    'Chi tiene stretta una cosa A COLORI non affonda del tutto nel Grigiore: le ancore funzionano.'],
  ['segreto_gemelli',       'SEGRETO: il demone SI NUTRE della lite infinita tra Federico e Daniele. Due gemelli che si danno ragione sono ILLEGGIBILI, per lui.'],
  ['foto_ricomposta',       'La foto dei gemelli è INTERA: due bambini che ridono della stessa cosa. La Casa non riesce a guardarla.'],
  ['indizio_spiriti',       'Il Grigiore non può toccare ciò che è già stato perso: gli SPIRITI passano ovunque, e vedono le porte che i vivi non vedono.'],
  ['segreto_trono',         'SEGRETO: Eleinad ogni notte DEVE tornare al Divano-Trono nella Sala della Switch, a ricaricarsi di vita finta. Lì, staccato dal Grigiore, è vulnerabile.'],
  ['sonnambuli_svegli',     'I Sonnambuli della Galleria sono SVEGLI. Camminano ancora piano, ma adesso sanno da che parte stare.'],
  ['zero_bevuta',           'La prima Zero da libero: Daniele l\'ha scolata in quattro secondi, a occhi chiusi, come un rito — ed è tornato LUI al settanta per cento. Il restante trenta è rancore utilissimo.'],
  ['dentro_eleinad',        'IL TWIST: questa non è casa di Daniele. La moquette respira, le pareti digeriscono. Siete DENTRO Eleinad. La geografia è anatomia.'],
  ['eleinad_vacilla',       'Gli spiriti l\'hanno attraversato e hanno riferito: Eleinad VACILLA. I suoi primi colpi saranno più deboli.'],
  ['via_biblioteca',        'La via della Biblioteca è aperta: il Manuale è vostro.'],
  ['via_porte',             'La via delle Porte è aperta: i ricordi corrotti non vi fermano più.'],
  ['via_cucina',            'La via della Cucina è aperta: siete scesi e risaliti.'],
  ['finestra_fotografata',  'Claudia ha fotografato la finestra di Daniele: la luce a metronomo, la prova che qualcosa dentro non è una TV.'],
  ['pacchi_controllati',    'I pacchi di Daniele: Coca Zero, Coca Zero, Coca Zero. Dodici giorni di consegne mai ritirate raccontano una scomparsa.'],
  ['fondo_caffe_letto',     'Il fondo del caffè di Daniele — fortissimo, come quello del nonno di Natalino. L\'odore racconta una mattina che la casa non ha potuto cancellare.'],
  ['partita_salvata',       'Avete salvato la partita di Mario Kart di Daniele: mezzo giro, congelato a metà curva. Quando tornerà, la troverà lì ad aspettarlo.'],
  ['stelle_finte_contate',  'Tre stelle dipinte nel lucernaio finto del pianerottolo impossibile: contate, memorizzate. Il cielo vero ne ha molte di più, e lo rivedrete.'],
  ['specchio_coperto',      'Lo specchio del bagno è coperto col telo della doccia: il riflesso in ritardo non vi guarderà più. Almeno da lì.'],
  ['cenere_studiata',       'La cenere grigia, aperta dalla torcia: dentro ci sono ancora ruggine, verde bottiglia, blu elettrico — pressati. Il Grigiore non distrugge: ACCUMULA, e ciò che è accumulato si può riprendere. Se c\'è un magazzino c\'è un inventario, e se c\'è un inventario si può fare un RESO.'],
  ['foto_gaeta_salvata',    'Avete staccato la foto di Gaeta dalla parete: il mare, gli amici, Emanuela che ride. Questa il Grigiore non la mangia — la tenete VOI.'],
  ['punto_inceppato_segnato','Il punto esatto dove Eleinad si è inceppato: "Milioni di persone lo fanno." Quando usa quel trucco, sapete dove si rompe.'],
  ['porte_misurate',        'Gaetano ha misurato le tre porte: la Biblioteca è la più larga, la Cucina la più stretta. Le dimensioni raccontano le priorità della casa.'],
  ['segnalibro_toccato',    'Il segnalibro a colori tra i libri di un Lettore Grigio: un disegno di bambino, sole giallo e casa rossa. Lo proteggeva anche nel sonno. Lo avete toccato, e ha resistito.'],
  ['titolo_incompiuto_letto','Il libro-cuore del Bibliotecario: "I CINQUE CHE..." — il titolo mai finito. Non l\'ha mai saputo nemmeno lui, per cosa fossero i cinque.'],
  ['d20_lanciato',          'Il d20 di Daniele, lanciato per la prima volta in vita sua: DICIASSETTE. Il numero suo — il compleanno, quello che chiama sempre "perché porta sfortuna agli ALTRI". Il dado ha aspettato anni e alla prima occasione ha firmato.'],
  ['riga_aggiunta_rosa',    'Nel diario di Rosa avete aggiunto una riga: "Cinque che tornano, e tornano, e tornano." Perché è quello che fate.'],
  ['ultimo_capitolo_letto', 'Le ultime parole del Capobranco prima di chiudersi: "FINE. (Più o meno.)" Si può mollare a metà ed essere felici. Tranne che per Daniele.'],
  ['treccia_portafortuna',  'La treccia di segnalibri recisa da Natalino: intrecciata come un portafortuna. Un trofeo professionale.'],
  ['loop_contato',          'Il loop sullo schermo della Sala della Switch: sorriso, cola, vittoria vuota. L\'avete contato. Ogni quindici secondi, tutto da capo. Il trailer della vita di un amico, fatto da chi lo odia.'],
  ['cavo_strappato',        'Un cavo HDMI strappato dalla parete della Sala della Switch: spesso come un polso, ancora caldo. Un pezzo dell\'impianto che teneva Daniele nel bozzolo.'],
  ['daniele_protetto',      'Prima del combattimento, avete messo Daniele al riparo dietro il trono. Il bozzolo è aperto, ma finché il Guardiano attacca, Daniele è dietro di voi.'],
  ['tasto_fotografato',     'Claudia ha fotografato il tasto rosso del Guardiano del Bozzolo: "CONTINUA A GUARDARE." Se è un tasto, ha un circuito. E i circuiti hanno punti deboli.'],
  ['silenzio_gemelli',      'Avete dato ai gemelli il loro silenzio: cinque minuti che valgono trent\'anni di discorsi non fatti. Certe paci non hanno bisogno di parole.'],
  ['piedistallo_distrutto', 'Il piedistallo della teca "I SEI" è in pezzi: non rimane niente su cui rimontare il trofeo. La collezione di Eleinad ha un buco permanente.'],
  ['monologo_studiato',     'Avete ascoltato Eleinad senza abboccare e memorizzato ogni parola. Le sue debolezze sono nel suo monologo: fame, vanità, un contratto d\'affitto che ha scritto lui.'],
  ['cerchio_completo',      'Gli altri si sono stretti in cerchio per aspettare i gemelli: Gaetano, Emanuela, Claudia, Natalino. Quando Federico e Daniele tornano, il cerchio è completo. Sei.'],
  ['nastro_sparito',        'Nella cameretta del 1994, dopo la pace: il nastro adesivo che divideva il pavimento in due metà NON C\'È PIÙ. Il litigio non è stato cancellato, è stato CHIUSO — e la Casa ha dovuto ritirare il suo attrezzo.'],
  ['battigia_vista',        'Sulla battigia di cenere, dove l\'onda si è ritirata: conchiglie rotte, un portachiavi a forma di racchetta e un\'impronta FRESCA del quarantaquattro, rivolta verso l\'acqua. Daniele gira ancora la sua Casa.'],
  ['foglio_volo_letto',     'I fogli di volo nella tasca del sedile 19A: qualcuno ci ha scritto sopra, una grafia piccola e nervosa. Un passeggero che non è mai atterrato.'],
  ['conchiglia_per_daniele', 'Una conchiglia dalla spiaggia grigia: la tenete per Daniele. Il mare vero suona diverso, e glielo farete sentire.'],
  ['consiglio_spiriti',     'Il consiglio della sala d\'aspetto: da spiriti non si esce, si RIENTRA. Serve che un vivo che ti vuole bene punti su di te qualcosa di suo — non un pensiero: un GESTO, dato gratis. E ogni carta messa da parte è un DEBITO che il demone spera vi scordiate.'],
  ['monitor_segreto',       'Nella Sala Controllo, in basso a destra, un monitor di SERVIZIO: trasmette Daniele in loop, quindici secondi per volta. Ogni stanza di questa casa guarda lo stesso, unico programma — e da qualche parte, in alto, lo trasmettono DAL VIVO.'],
  ['bottiglia_colore',      'Una bottiglia di colore, nascosta in fondo a un cassetto della cucina: qualcuno l\'ha messa lì prima di voi. Qualcuno che sapeva dove cercare.'],
  ['salone_benedetto',      'Il salone di Natalino, quello vero — ricordato dalla porta numero 7: i clienti, il profumo di lacca, le forbici giapponesi. Natalino ha benedetto questa memoria e l\'ha strappata al grigio.'],
  ['braciere_agosto',       'Dove bruciava il fuoco finto del ferragosto rubato è rimasto un braciere di colore VERO: cinque minuti seduti intorno, senza parlarne, e un brindisi con la Coca Zero immaginaria — "al quattordici agosto. Quello vero. E al prossimo."'],
  ['toga_targhetta',        'La targhetta cucita nella toga: era l\'Avvocato del Grigio, novantasei cause vinte su novantasette. La seconda riga — quella dell\'unica persa — se l\'era ricamata da solo. Il Grigiore non l\'ha preso per la causa perduta: per le novantasei che ha smesso di contare.'],
  ['pianta_salvata',        'La pianta della Casa, ricostruita dal fumo del tronello e ridisegnata a memoria da Claudia sul telefono: corridoi, stanze, e in cima un rettangolo grande con dentro un rettangolo piccolo — uno schermo davanti a un divano.'],
  ['segno_muro',            'Il segno sul muro della cattedrale, dopo il palleggio: un cerchio di vernice gialla e quattro crepe che partono da lì. Il colore non lo nutre — gli fa danno STRUTTURALE. E voi ne avete una borsa piena.'],
  ['voce_muro',             'La voce dentro il muro del salotto, a quaranta centimetri dall\'orecchio di Natalino: ripassava il VOSTRO piano, parola per parola, con l\'accento tutto sbagliato. Da stanotte i piani si scrivono, non si dicono.'],
  ['libro_colori',          'Il catalogo tipografico dei colori, caduto in biblioteca e aperto sui blu: un rettangolino cerchiato a penna dal gemello — "Blu Serapo, ore 19:10, agosto. Un colore da tenere in tasca." Si era fatto la scorta prima che gliela chiedessero.'],
  ['cucina_dopo_botola',    'Sul bancone della cucina fredda, comparso dal niente: un omaggio della ditta — una Boccata di Colore, un tarallo e un cartoncino unto. "Voi non avete visto niente della mia contabilità, io non ho visto niente delle vostre mani. — Il M."'],
  ['postit_retro',          'Il retro del post-it della parmigiana, scritto di corsa e premendo fino a bucare la carta: "Se leggete questo, io non sono in cucina. TAPPETO. →↓" Sotto il tappeto c\'è una botola, e Daniele l\'ha lasciata aperta per voi.'],
  ['esercizio_daniele',     'Nel libro di fisica di Luca Giunti, pagina 214: l\'esercizio dei moti armonici svolto a matita da Daniele — passaggio giusto — e una nota fuori tema, "torna al punto di partenza ogni sette decimi di secondo, per sempre, senza stancarsi. VOGLIO ESSERE UNA MOLLA."'],
  ['nota_tripla',           'L\'ultima pagina del Manuale, sottolineata TRE volte con tre penne diverse: "Se conosci il trucco, il trucco non funziona. VALE ANCHE PER QUELLO GRANDE." La terza sottolineatura era per voi.'],
  ['occhio_pozzetto',       'Il congelatore a pozzetto della cucina fredda: dentro, un blocco di spesa VERA che si è mosso e vi ha indicato una crepa in alto, da cui filtra luce verde. Perfino il mostro nel freezer tifa per voi.'],
  ['piatto_per_daniele',    'Un piatto preparato per Daniele: la parmigiana di Emanuela, porzione da fame vera. Quando lo troverete, sarà ancora caldo.'],
  ['programma_svelato',     'Cosa dava, il programma grigio: NIENTE. Solo la sigla, sempre la sigla, per anni — perché aspettare una cosa bella non sembra tempo perso. Il Grigiore non incatena: ACCOMODA. E la poltrona era comodissima.'],
  ['teca_nome_letto',       'La targhetta della teca più grande della Galleria: "RINO — piano terra, interno 2. Rideva alle repliche." E sotto: "Acquisito per abbandono: nessuno lo chiamava da 3 anni, 2 mesi, 11 giorni." La Casa non rapisce: RACCOGLIE.'],
  ['signora_consiglio',     'Il consiglio di ADELE, la signora in vestaglia della Galleria — per anni "quella della quaranta-due": "Non combattere il grigio coi pugni: i pugni si stancano. Combattilo coi NOMI. Il grigio odia chi ha un nome, perché il nome è un colore che non sbiadisce."'],
  ['biografia_sfogliata',   'Avete sfogliato la biografia di Eleinad senza specchio: figure, schemi, frammenti. Non tutto, ma abbastanza per sapere che il demone ha una STORIA — e le storie hanno un finale.'],
  ['nome_gridato',          'Avete chiamato Daniele per nome, FORTE, mentre il bozzolo si apriva. La voce è un colore che nessun filamento può filtrare.'],
  ['camerino_visto',        'Lo specchio, guardato dal SUO lato: un salotto grigio identico a questo, e lui davanti al vetro che PROVA le espressioni di Daniele — otto tentativi per un sorriso. Un mostro che si esercita di nascosto è un mostro che può sbagliare.'],
  ['contraddizione_smascherata', 'Eleinad si contraddice sulla propria origine: prima un riflesso rimasto attaccato a uno specchio, poi "l\'interesse composto della pigrizia altrui". Mente pure sul curriculum — e chi si gonfia il ruolo al colloquio ha paura del colloquio.'],
  ['furto_a_libro',         'Il Mercante ha messo la Boccata rubata a libro contabile, con la data di stanotte: niente Riscossore, "siete colleghi". Arriverà una FATTURA, quando fa più male. Il Grigiore non odia: ARCHIVIA.'],
  ['regalo_conchiglia',     'La conchiglia di Gaeta, consegnata a Daniele nella Sala della Switch: quattro secondi di mare vero contro tre giorni di vita finta. Se l\'è messa in tasca e la tiene stretta con la mano da fuori.'],
  ['regalo_piatto',         'Il piatto tenuto da parte, consegnato: parmigiana ancora CALDA in una casa dove niente è caldo. Verdetto ufficiale di Daniele: "la mozzarella andava asciugata meglio". Poi l\'ha finito in quaranta secondi.'],
  ['regalo_foto',           'La foto di Gaeta, quella che resiste, consegnata a Daniele: se l\'è piegata lungo un margine vuoto e messa nella tasca del petto. "Adesso ho una cosa da fargli vedere anch\'io."'],
];

/* Mappa del mondo: le zone della Casa (per il canvas della mappa).
   Gli array `scenes` si CALCOLANO dalla campagna: niente elenchi a mano da tenere aggiornati. */
const WORLD_MAP = [
  { key: 'strada',       label: 'La Strada',      x: 0.10, y: 0.85, scenes: [] },
  { key: 'palazzo',      label: 'Il Palazzo',     x: 0.26, y: 0.72, scenes: [] },
  { key: 'appartamento', label: 'L\'Appartamento', x: 0.42, y: 0.60, scenes: [] },
  { key: 'salotto',      label: 'Il Salotto',     x: 0.50, y: 0.42, scenes: [] },
  { key: 'biblioteca',   label: 'La Biblioteca',  x: 0.20, y: 0.30, scenes: [] },
  { key: 'porte',        label: 'Le Porte',       x: 0.50, y: 0.14, scenes: [] },
  { key: 'cucina',       label: 'La Cucina',      x: 0.78, y: 0.52, scenes: [] },
  { key: 'sottoscala',   label: 'Il Sottoscala',  x: 0.88, y: 0.78, scenes: [] },
  { key: 'switch',       label: 'La Sala Switch', x: 0.74, y: 0.24, scenes: [] },
  { key: 'cattedrale',   label: 'La Cattedrale',  x: 0.90, y: 0.10, scenes: [] },
];

/* location → zona della mappa */
const MAP_ZONE_BY_LOCATION = {
  strada: 'strada',
  palazzo: 'palazzo', pianerottolo: 'palazzo',
  appartamento: 'appartamento',
  corridoio: 'salotto', salotto: 'salotto',
  biblioteca: 'biblioteca',
  porte: 'porte', cameretta: 'porte', spiaggia_grigia: 'porte', cabina: 'porte', stanza_sommersa: 'porte',
  cucina_fredda: 'cucina',
  sottoscala: 'sottoscala', mercante: 'sottoscala', galleria: 'sottoscala',
  sala_switch: 'switch', trono: 'switch',
  cattedrale: 'cattedrale', alba_colori: 'cattedrale',
};
for (const [id, scene] of Object.entries(CAMPAIGN)) {
  const zone = WORLD_MAP.find(w => w.key === MAP_ZONE_BY_LOCATION[scene.location]);
  if (zone) zone.scenes.push(id);
}
